### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by rintoshukla** [alexantoniades/python-RN2483#1] opened 2019-11-27 08:51 UTC
Installation issue: - 
No library found to install which results in the error while executing line - 
"uart = serial.Serial(PORT, BAUDRATE)".
Error is - TypeError: 'module' object is not callable

Below is the installation log:
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
creating lora_rn2483.egg-info
writing lora_rn2483.egg-info/PKG-INFO
writing dependency_links to lora_rn2483.egg-info/dependency_links.txt
writing requirements to lora_rn2483.egg-info/requires.txt
writing top-level names to lora_rn2483.egg-info/top_level.txt
writing manifest file 'lora_rn2483.egg-info/SOURCES.txt'
reading manifest file 'lora_rn2483.egg-info/SOURCES.txt'
writing manifest file 'lora_rn2483.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
**warning: install_lib: 'build/lib' does not exist -- no Python modules to install**

**Comment by alexantoniades** [comment] 2020-02-11 11:35
Hey, thanks for leaving an issue. I just noticed this was a problem. Seems setup.py isn't installing the module in /lib, try manually copying the rn2483.py file to your Python's path. On windows, for me it was in C:\Python38\Lib and on linux at /usr/lib/python3. place the rn2483.py file with its /src directory and it should work as a temporary patch up. The problem is nor with serial and rather with the packaging. Something broke since i published it in PyPI, going to work on a fix.

**Comment by alexantoniades** [comment] 2020-02-11 11:35
Closed by accident

**Comment by alexantoniades** [comment] 2020-04-26 07:12
No activity

**Closed** 2020-04-26 07:12 UTC

**Comment by LucienCamuglia** [comment] 2020-10-22 13:16
Same issue...
How did you resolve it ?

**Comment by alexantoniades** [comment] 2020-10-22 13:44
This was not resolved, no. 

I've abandoned this project since I am not satisfied with the quality of code.

Though I am planning on rewritting it properly soon.
